services:
# ---------------------------------------website-------------------------------------------
  website:
    build:
      context: ./web/
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
      - "5555:5555"
    container_name: website
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - object_store
    volumes:
      - ./web/:/app
    environment:
      - NODE_ENV=development
    command: bash -c "rm -rf .next && npm run dev"

# ------------------------------------load_balancer-----------------------------------------
  load_balancer:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - website
    ports:
      - "80:80"

# ----------------------------------database and related to it------------------------------------

  mongo1:
    image: mongo:6
    container_name: mongo1
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/mongo1_data:/data/db
    command: mongod --replSet rs --bind_ip localhost,mongo1

  mongo2:
    image: mongo:6
    container_name: mongo2
    ports:
      - 27018:27017
    volumes:
      - ./data/mongo/mongo2_data:/data/db
    command: mongod --replSet rs --bind_ip localhost,mongo2
  
  mongo3:
    image: mongo:6
    container_name: mongo3
    ports:
      - 27019:27017
    volumes:
      - ./data/mongo/mongo3_data:/data/db
    command: mongod --replSet rs --bind_ip localhost,mongo3

  mongo-express:
    image: mongo-express
    container_name: mongo_panel
    restart: always
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo1:27017/
      ME_CONFIG_BASICAUTH: false

  object_store:
    build: ./aws/
    container_name: object_store
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - ./data/aws:/persisted-data
      - "/var/run/docker.sock:/var/run/docker.sock"

# -----------------------------------pdf operations api--------------------------------------------------
  pdf-api:
    image: frooodle/s-pdf:latest
    container_name: pdf-api
    ports:
      - '4000:8080'
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
      - UI_APPNAME=PDFs
      - UI_HOMEDESCRIPTION=A versatile PDF app that provides a suite of services for manipulating PDFs, including converting, merging, splitting, rotating, and securing documents, ensuring seamless document management
      - UI_APPNAMENAVBAR=PDFs